### ISSUE TITLE
App_todo not created with docker

### ISSUE THREAD

**Issue by j2l** [apioo/fusio#126]
Fusio tables are present, but there are no app_todo table in the MySQL server when using docker.
Actions and routes are created though.

**Comment by k42b3** [comment]
By default Fusio uses a sqlite database inside the docker container but this is only a demo. In a production app you would setup a second database, configure this database in the `connections.yaml` and then use this connection in your action. So your app is always complete independent of the Fusio database. This is also needed for the migration tool to adjust the database.

**Comment by j2l** [comment]
Thanks!
Sorry, I wasn't precise enough:
Actually, when I execute the action in Fusio docker I get an error stating the app_todo doesn't exist.

**Comment by k42b3** [comment]
Ok, if I use the fusio docker repo and create the system through:

```
docker-compose up
```

I can not reproduce this error. How do you run the docker image?

**Comment by j2l** [comment]
Hi,
I used `docker-compose up` too I think.

**Comment by j2l** [comment]
I flushed both containers and built them again with `docker-compose up` and got the same issue:
Executing the TODO Collection Action I get:

```
Response 500
An exception occurred while executing 'SELECT COUNT(*) FROM app_todo': SQLSTATE[HY000]: General error: 1 no such table: app_todo in /var/www/html/fusio/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php on line 58

#0 /var/www/html/fusio/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/html/fusio/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT COUNT(*)...', Array)
#2 /var/www/html/fusio/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(541): Doctrine\DBAL\Connection->executeQuery('SELECT COUNT(*)...', Array, Array)
#3 /var/www/html/fusio/src/Todo/collection.php(15): Doctrine\DBAL\Connection->fetchColumn('SELECT COUNT(*)...')
#4 /var/www/html/fusio/vendor/fusio/adapter-php/src/Action/PhpEngine.php(77): require('/var/www/html/f...')
#5 /var/www/html/fusio/vendor/fusio/adapter-php/src/Action/PhpEngine.php(63): Fusio\Adapter\Php\Action\runScript('/var/www/html/f...', Array)
#6 /var/www/html/fusio/vendor/fusio/engine/src/Processor.php(72): Fusio\Adapter\Php\Action\PhpEngine->handle(Object(Fusio\Engine\Request), Object(Fusio\Engine\Parameters), Object(Fusio\Engine\Context))
#7 /var/www/html/fusio/vendor/fusio/impl/src/Service/Action/Executor.php(101): Fusio\Engine\Processor->execute(2, Object(Fusio\Engine\Request), Object(Fusio\Engine\Context))
#8 /var/www/html/fusio/vendor/fusio/impl/src/Backend/Api/Action/Execute.php(79): Fusio\Impl\Service\Action\Executor->execute(2, 'GET', Array, Array, Array, Object(PSX\Record\Record))
#9 /var/www/html/fusio/vendor/psx/framework/src/Controller/SchemaApiAbstract.php(138): Fusio\Impl\Backend\Api\Action\Execute->doPost(Object(PSX\Record\Record))
#10 /var/www/html/fusio/vendor/psx/framework/src/Filter/ControllerExecutor.php(60): PSX\Framework\Controller\SchemaApiAbstract->onPost()
#11 /var/www/html/fusio/vendor/psx/framework/src/Filter/FilterChain.php(79): PSX\Framework\Filter\ControllerExecutor->handle(Object(PSX\Http\Request), Object(PSX\Http\Response), Object(PSX\Framework\Filter\FilterChain))
#12 /var/www/html/fusio/vendor/psx/framework/src/Filter/Oauth2Authentication.php(111): PSX\Framework\Filter\FilterChain->handle(Object(PSX\Http\Request), Object(PSX\Http\Response))
#13 /var/www/html/fusio/vendor/psx/framework/src/Filter/FilterChain.php(79): PSX\Framework\Filter\Oauth2Authentication->handle(Object(PSX\Http\Request), Object(PSX\Http\Response), Object(PSX\Framework\Filter\FilterChain))
#14 /var/www/html/fusio/vendor/psx/framework/src/Filter/UserAgentEnforcer.php(41): PSX\Framework\Filter\FilterChain->handle(Object(PSX\Http\Request), Object(PSX\Http\Response))
#15 /var/www/html/fusio/vendor/psx/framework/src/Filter/FilterChain.php(79): PSX\Framework\Filter\UserAgentEnforcer->handle(Object(PSX\Http\Request), Object(PSX\Http\Response), Object(PSX\Framework\Filter\FilterChain))
#16 /var/www/html/fusio/vendor/psx/framework/src/Loader/Loader.php(146): PSX\Framework\Filter\FilterChain->handle(Object(PSX\Http\Request), Object(PSX\Http\Response))
#17 /var/www/html/fusio/vendor/psx/framework/src/Loader/Loader.php(117): PSX\Framework\Loader\Loader->executeController(Object(Fusio\Impl\Backend\Api\Action\Execute), Object(PSX\Http\Request), Object(PSX\Http\Response))
#18 /var/www/html/fusio/vendor/psx/framework/src/Dispatch/Dispatch.php(121): PSX\Framework\Loader\Loader->load(Object(PSX\Http\Request), Object(PSX\Http\Response), Object(PSX\Framework\Loader\Context))
#19 /var/www/html/fusio/vendor/psx/framework/src/Environment/WebServer/Engine.php(47): PSX\Framework\Dispatch\Dispatch->route(Object(PSX\Http\Request), Object(PSX\Http\Response))
#20 /var/www/html/fusio/vendor/psx/framework/src/Environment/Environment.php(67): PSX\Framework\Environment\WebServer\Engine->serve(Object(PSX\Framework\Dispatch\Dispatch), Object(PSX\Framework\Config\Config))
#21 /var/www/html/fusio/public/index.php(29): PSX\Framework\Environment\Environment->serve()
#22 {main}
```

**Comment by j2l** [comment]
Looking for " todo-app.db" in [fusio-docker](https://github.com/apioo/fusio-docker/search?utf8=%E2%9C%93&q=todo-app&type=), I can't find anything.

**Comment by j2l** [comment]
Thank you!
I tested openapi in the past and wondered if there was another tool. But it's still great to start.

On the app_todo side, unfortunately it's not working, same error.

I updated git repo using github desktop, checked a file to see that update is here, then I flushed containers and `docker-compose up` (both containers visible in kitematic) but I still get:
`An exception occurred while executing 'SELECT COUNT(*) FROM app_todo': SQLSTATE[HY000]: General error: 1 no such table: app_todo in /var/www/html/fusio/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php on line 58`

**Comment by k42b3** [comment]
Mhh ok, did you have actually removed the Fusio container through:

```
docker rmi -f [image_id]
```

also if you recreate the image you need to remove the files from the database container so that Fusio triggers a complete new installation. Otherwise the database contains already an entry in the migration table and thus the migration is not executed.

**Comment by j2l** [comment]
You're right. I removed (flushed) images using Kitematic but it didn't delete images, it just removed containers.
So I rmi -f mysql and fusio images, docker-compose up the latest fusio-docker from github, but still no luck :) Sam error.
I really expected this one to work.

**Comment by k42b3** [comment]
ok, so the problem is that the migration is not executed, during deploy you should see the following line:

```
- [EXECUTED] migration Default-Connection resources/migration/v1_schema.php
```

The is because the `mysql_fusio_1` container is not rebuilded instead it uses an existing database. If you delete this database you should see the migration line. Iam confident that this should solve the problem ;)

**Comment by j2l** [comment]
OK. I dropped fusio database.
Starting the fusio container confirm db is not present anymore:
```
In AbstractMySQLDriver.php line 103:
                                                                               
  An exception occured in driver: SQLSTATE[HY000] [1049] Unknown database 'fu  
  sio'                                                                         
                                                                               
2018-02-02T07:46:43.623148200Z 
In PDOConnection.php line 47:
                                                   
  SQLSTATE[HY000] [1049] Unknown database 'fusio'  
                                                   
2018-02-02T07:46:43.623225062Z 
In PDOConnection.php line 43:
                                                   
  SQLSTATE[HY000] [1049] Unknown database 'fusio'  
                                                   
2018-02-02T07:46:43.623423463Z 
system:install
2018-02-02T07:46:43.623453448Z 
Loaded definition /var/www/html/fusio/vendor/fusio/adapter-amqp/src/../definition.json
2018-02-02T07:46:44.135644924Z 
In ConnectionException.php line 42:
                                   
  There is no active transaction.  
                                   
2018-02-02T07:46:44.157062610Z 
system:register [-y|--yes] [--] <class> [<path>]
2018-02-02T07:46:44.157094194Z 
Loaded definition /var/www/html/fusio/vendor/fusio/adapter-beanstalk/src/../definition.json
2018-02-02T07:46:44.321267666Z 
In ConnectionException.php line 42:
                                   
  There is no active transaction.  

...
```
But it still doesn't migrate. (May be testing the db and migrate could be added at container startup?)

Then I removed the fusio image (not the mysql since it has embedded tables):
```
$ docker ps -a
CONTAINER ID        IMAGE                          COMMAND                CREATED             STATUS                      PORTS                   NAMES
63d47916ad18        phpmyadmin/phpmyadmin:latest   "/run.sh phpmyadmin"   6 days ago          Up 26 minutes               0.0.0.0:32768->80/tcp   phpmyadmin
$ docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
mysql                   5.7                 f008d8ff927d        2 weeks ago         409MB
phpmyadmin/phpmyadmin   latest              19c3875df23d        5 weeks ago         104MB
```

Then I `docker-compose up` and get:
```
docker-compose up
Pulling fusio (fusio/fusio:latest)...
latest: Pulling from fusio/fusio
1be7f2b886e8: Pull complete
6fbc4a21b806: Pull complete
c71a6f8e1378: Pull complete
4be3072e5a37: Pull complete
06c6d2f59700: Pull complete
ad5fc3a6617f: Pull complete
323673dcf094: Pull complete
b0860590963b: Pull complete
6fd4e16ba7e4: Pull complete
dde18a913d26: Pull complete
7a42aeb35161: Pull complete
3c481cb61a14: Pull complete
3ae438f46566: Pull complete
74a1cf8e0ca1: Pull complete
7f0093aff157: Pull complete
f6892404d121: Pull complete
901905928970: Pull complete
1af75477048f: Pull complete
d6651f49c619: Pull complete
e68c6cbb8174: Pull complete
28c0d2b8053e: Pull complete
a86a816dd641: Pull complete
675df0ccdbd5: Pull complete
efaf44b211d5: Pull complete
fadaaecd38f7: Pull complete
7fda753c9f23: Pull complete
fa1438ad4f5b: Pull complete
565bce7d3ccc: Pull complete
e2a9269c927f: Pull complete
82ea2950cb2f: Pull complete
a4a6fab89e64: Pull complete
b11b41ce5dc2: Pull complete
9e9b65afab30: Pull complete
b213ddda9692: Pull complete
53c381b9de3b: Pull complete
6631c36fe828: Pull complete
2d3fb288f826: Pull complete
8739d0ea5210: Pull complete
776a17036788: Pull complete
0c241372e16a: Pull complete
Digest: sha256:411df5e7b62c7947ea1ea65216c4a9a7bd0cc97a9da14200ba784ed59dbe83d9
Creating fusiodocker_mysql_fusio_1 ... done
Creating fusiodocker_mysql_fusio_1 ... 
Creating fusiodocker_fusio_1       ... done
Attaching to fusiodocker_mysql_fusio_1, fusiodocker_fusio_1
mysql_fusio_1  | 2018-02-02T08:05:28.693638Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql_fusio_1  | 2018-02-02T08:05:28.701754Z 0 [Note] mysqld (mysqld 5.7.21) starting as process 1 ...
mysql_fusio_1  | 2018-02-02T08:05:28.717386Z 0 [Warning] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
mysql_fusio_1  | 2018-02-02T08:05:28.730218Z 0 [Note] InnoDB: PUNCH HOLE support available
mysql_fusio_1  | 2018-02-02T08:05:28.730818Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql_fusio_1  | 2018-02-02T08:05:28.732501Z 0 [Note] InnoDB: Uses event mutexes
mysql_fusio_1  | 2018-02-02T08:05:28.733213Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mysql_fusio_1  | 2018-02-02T08:05:28.734074Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.3
mysql_fusio_1  | 2018-02-02T08:05:28.734959Z 0 [Note] InnoDB: Using Linux native AIO
mysql_fusio_1  | 2018-02-02T08:05:28.738327Z 0 [Note] InnoDB: Number of pools: 1
mysql_fusio_1  | 2018-02-02T08:05:28.741953Z 0 [Note] InnoDB: Using CPU crc32 instructions
mysql_fusio_1  | 2018-02-02T08:05:28.745600Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
mysql_fusio_1  | 2018-02-02T08:05:28.764482Z 0 [Note] InnoDB: Completed initialization of buffer pool
mysql_fusio_1  | 2018-02-02T08:05:28.770618Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql_fusio_1  | 2018-02-02T08:05:28.818577Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
mysql_fusio_1  | 2018-02-02T08:05:28.997381Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql_fusio_1  | 2018-02-02T08:05:28.999839Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql_fusio_1  | 2018-02-02T08:05:29.205991Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql_fusio_1  | 2018-02-02T08:05:29.293027Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
mysql_fusio_1  | 2018-02-02T08:05:29.294526Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
mysql_fusio_1  | 2018-02-02T08:05:29.296234Z 0 [Note] InnoDB: Waiting for purge to start
mysql_fusio_1  | 2018-02-02T08:05:29.350265Z 0 [Note] InnoDB: 5.7.21 started; log sequence number 14173370
mysql_fusio_1  | 2018-02-02T08:05:29.351641Z 0 [Note] Plugin 'FEDERATED' is disabled.
mysql_fusio_1  | 2018-02-02T08:05:29.356170Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql_fusio_1  | 2018-02-02T08:05:29.531864Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
mysql_fusio_1  | 2018-02-02T08:05:29.554795Z 0 [Note] InnoDB: Buffer pool(s) load completed at 180202  8:05:29
mysql_fusio_1  | 2018-02-02T08:05:29.556814Z 0 [Warning] CA certificate ca.pem is self signed.
mysql_fusio_1  | 2018-02-02T08:05:29.617633Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
mysql_fusio_1  | 2018-02-02T08:05:29.618944Z 0 [Note] IPv6 is available.
mysql_fusio_1  | 2018-02-02T08:05:29.619946Z 0 [Note]   - '::' resolves to '::';
mysql_fusio_1  | 2018-02-02T08:05:29.620789Z 0 [Note] Server socket created on IP: '::'.
mysql_fusio_1  | 2018-02-02T08:05:30.073703Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
mysql_fusio_1  | 2018-02-02T08:05:30.074753Z 0 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
mysql_fusio_1  | 2018-02-02T08:05:30.075221Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_fusio_1  | 2018-02-02T08:05:30.076386Z 0 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
mysql_fusio_1  | 2018-02-02T08:05:30.076847Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_fusio_1  | 2018-02-02T08:05:30.078044Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
mysql_fusio_1  | 2018-02-02T08:05:30.155279Z 0 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
mysql_fusio_1  | 2018-02-02T08:05:30.156367Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_fusio_1  | 2018-02-02T08:05:30.398050Z 0 [Note] Event Scheduler: Loaded 0 events
mysql_fusio_1  | 2018-02-02T08:05:30.399029Z 0 [Note] mysqld: ready for connections.
mysql_fusio_1  | Version: '5.7.21'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
mysql_fusio_1  | 2018-02-02T08:05:30.423532Z 2 [Note] Access denied for user 'root'@'172.18.0.3' (using password: NO)
fusio_1        | /var/www/html/fusio /
fusio_1        | Check failed
fusio_1        | 
fusio_1        | In AbstractMySQLDriver.php line 103:
fusio_1        |                                                                                
fusio_1        |   An exception occured in driver: SQLSTATE[HY000] [1049] Unknown database 'fu  
fusio_1        |   sio'                                                                         
fusio_1        |                                                                                
fusio_1        | 
fusio_1        | In PDOConnection.php line 47:
fusio_1        |                                                    
fusio_1        |   SQLSTATE[HY000] [1049] Unknown database 'fusio'  
fusio_1        |                                                    
fusio_1        | 
fusio_1        | In PDOConnection.php line 43:
fusio_1        |                                                    
fusio_1        |   SQLSTATE[HY000] [1049] Unknown database 'fusio'  
fusio_1        |                                                    
fusio_1        | 
fusio_1        | system:install
fusio_1        | 
fusio_1        | Loaded definition /var/www/html/fusio/vendor/fusio/adapter-amqp/src/../definition.json
fusio_1        | 
fusio_1        | In ConnectionException.php line 42:
fusio_1        |                                    
fusio_1        |   There is no active transaction.  
fusio_1        |                                    
fusio_1        | 
fusio_1        | system:register [-y|--yes] [--] <class> [<path>]
fusio_1        | 
fusio_1        | Loaded definition /var/www/html/fusio/vendor/fusio/adapter-beanstalk/src/../definition.json
fusio_1        | 
fusio_1        | In ConnectionException.php line 42:
fusio_1        |                                    
fusio_1        |   There is no active transaction.  
fusio_1        |                                    
fusio_1        | 
fusio_1        | system:register [-y|--yes] [--] <class> [<path>]
fusio_1        | 
fusio_1        | Loaded definition /var/www/html/fusio/vendor/fusio/adapter-elasticsearch/src/../definition.json
fusio_1        | 
fusio_1        | In ConnectionException.php line 42:
fusio_1        |                                    
fusio_1        |   There is no active transaction.  
fusio_1        |                                    
fusio_1        | 
fusio_1        | system:register [-y|--yes] [--] <class> [<path>]
fusio_1        | 
fusio_1        | Loaded definition /var/www/html/fusio/vendor/fusio/adapter-memcache/src/../definition.json
fusio_1        | 
fusio_1        | In ConnectionException.php line 42:
fusio_1        |                                    
fusio_1        |   There is no active transaction.  
fusio_1        |                                    
fusio_1        | 
fusio_1        | system:register [-y|--yes] [--] <class> [<path>]
fusio_1        | 
fusio_1        | Loaded definition /var/www/html/fusio/vendor/fusio/adapter-mongodb/src/../definition.json
fusio_1        | 
fusio_1        | In ConnectionException.php line 42:
fusio_1        |                                    
fusio_1        |   There is no active transaction.  
fusio_1        |                                    
fusio_1        | 
fusio_1        | system:register [-y|--yes] [--] <class> [<path>]
fusio_1        | 
fusio_1        | Loaded definition /var/www/html/fusio/vendor/fusio/adapter-redis/src/../definition.json
fusio_1        | 
fusio_1        | In ConnectionException.php line 42:
fusio_1        |                                    
fusio_1        |   There is no active transaction.  
fusio_1        |                                    
fusio_1        | 
fusio_1        | system:register [-y|--yes] [--] <class> [<path>]
fusio_1        | 
fusio_1        | Loaded definition /var/www/html/fusio/vendor/fusio/adapter-soap/src/../definition.json
fusio_1        | 
fusio_1        | In ConnectionException.php line 42:
fusio_1        |                                    
fusio_1        |   There is no active transaction.  
fusio_1        |                                    
fusio_1        | 
fusio_1        | system:register [-y|--yes] [--] <class> [<path>]
fusio_1        | 
fusio_1        | Check failed
fusio_1        | 
fusio_1        | In AbstractMySQLDriver.php line 103:
fusio_1        |                                                                                
fusio_1        |   An exception occured in driver: SQLSTATE[HY000] [1049] Unknown database 'fu  
fusio_1        |   sio'                                                                         
fusio_1        |                                                                                
fusio_1        | 
fusio_1        | In PDOConnection.php line 47:
fusio_1        |                                                    
fusio_1        |   SQLSTATE[HY000] [1049] Unknown database 'fusio'  
fusio_1        |                                                    
fusio_1        | 
fusio_1        | In PDOConnection.php line 43:
fusio_1        |                                                    
fusio_1        |   SQLSTATE[HY000] [1049] Unknown database 'fusio'  
fusio_1        |                                                    
fusio_1        | 
fusio_1        | system:install
fusio_1        | 
fusio_1        | Check failed
fusio_1        | 
fusio_1        | In AbstractMySQLDriver.php line 103:
fusio_1        |                                                                                
fusio_1        |   An exception occured in driver: SQLSTATE[HY000] [1049] Unknown database 'fu  
fusio_1        |   sio'                                                                         
fusio_1        |                                                                                
fusio_1        | 
fusio_1        | In PDOConnection.php line 47:
fusio_1        |                                                    
fusio_1        |   SQLSTATE[HY000] [1049] Unknown database 'fusio'  
fusio_1        |                                                    
fusio_1        | 
fusio_1        | In PDOConnection.php line 43:
fusio_1        |                                                    
fusio_1        |   SQLSTATE[HY000] [1049] Unknown database 'fusio'  
fusio_1        |                                                    
fusio_1        | 
fusio_1        | user:add [-s|--status [STATUS]] [-u|--username [USERNAME]] [-e|--email [EMAIL]] [-p|--password [PASSWORD]]
fusio_1        | 
fusio_1        | 
fusio_1        | In ConnectionException.php line 42:
fusio_1        |                                    
fusio_1        |   There is no active transaction.  
fusio_1        |                                    
fusio_1        | 
fusio_1        | system:deploy [<file>]
fusio_1        | 
fusio_1        | /
fusio_1        | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
```
I confirm that fusio database is absent.

And ... I'm stuck. 
At this point, if I `rmi `the mysql image to `docker-compose up`, it will re-download the full image build the database and ignore migration like before. 

BTW, this also mean that if you already have a mysql container for your API, you might not be able to install fusio docker (existing mysql container without fusio database, same scenario). 
This would ruin the interest of adding fusio above an existing API running in containers.

**Comment by k42b3** [comment]
Ok, so to test this I would recommend to remove the fusio and mysql docker image and the mysql folder in `/db`. If you then run `docker-compose up` it should create the db and Fusio should be able to connect to this db.

We have also a test case on travis which tests the setup:
https://travis-ci.org/apioo/fusio-docker

Because we use the -d flag you cant see the output of the running container. But this should work also for your case.

> BTW, this also mean that if you already have a mysql container for your API, you might not be able to install fusio docker (existing mysql container without fusio database, same scenario).
> This would ruin the interest of adding fusio above an existing API running in containers.

I can understand your thought, but in general with docker images you have always one database per container and Fusio needs a dedicated database for installation. So you always need a dedicated database container for Fusio and should not use an existing one. If Fusio is then installed you can easily create new connections to different and already existing databases which then work with your app.

**Comment by j2l** [comment]
Thank you for your perseverance, It's working now! Killing the image didn't remove the db.
Thanks also for the details about CI.
