### ISSUE TITLE
How to enable CORS in fusio?

### ISSUE THREAD

**Issue by subangkit** [apioo/fusio#52]
I'am currently testing fusio with front end application. but facing problem with preflight from browser coz fusio not accepting CORS. 

How to setting CORS in fusio ?

**Comment by k42b3** [comment]
Hi, in the admin panel you can set the `CORS` header under settings `cors_allow_origin` and then use `*` or a specific url. Each API response contains then the `Access-Control-Allow-Origin` header.

**Comment by k42b3** [comment]
I close this issue since it looks like the problem was solved. If this is not the case feel free to reopen the issue.

**Comment by boknoypatotoy** [comment]
hi chrisapp, there is no cors_allow_origin in the settings Fusio 0.5.0

**Comment by chriskapp** [comment]
Hi, @boknoypatotoy so the `psx_cors_origin` setting must be placed at the `configuration.php` file and not at the backend settings. You can add the following setting to the configuration:

```
'psx_cors_origin'         => '*',
```

But in general it is not needed to change this settings, Fusio sets the cors header automatically in case the Origin header is available.

**Comment by ratsey** [comment]
Is this just a plain entry in the configuration.php in the fusio directory? ie, I should be able to add


```
if (!getenv('FUSIO_ENV')) {
    $dotenv = new \Symfony\Component\Dotenv\Dotenv();
    $dotenv->load(__DIR__ . '/.env');
}

return [

    'psx_cors_origin'         => 'x.y.com,someother.domain.com',
    
    // Whether the implicit flow is allowed. This is mostly needed for 
    // javascript apps
    'fusio_grant_implicit'    => true,
```

I have my calling URLs added but still get errors:

`SEC7120: [CORS] The origin 'http://x.y.com' did not find 'http://x.y.com' in the Access-Control-Allow-Origin response header for cross-origin  resource at 'http://[myRESTEndPoint]'.`

**Comment by ratsey** [comment]
I tried setting it just to

`'psx_cors_origin'         => '*',`

and this works from Insomnia - if I set a request header for 'Origin' to 'x.y.com' then I see the header response includes

`access-control-allow-origin *`

If I don't set that header in Insomnia, I still get a proper response with data returned.

I tried setting a header value to my host in the Angular code I'm calling from, but I get yelled at by the Chrome browser that I've set something I'm not allowed to (which makes sense to prevent spoofing). **But** - from the error I get in Chrome when running without setting it explicitly, the Origin is clearly being sent correctly anyway. So why nothing returned and why am I CORS denied when running from Chrome?

**Comment by dgambin** [comment]
I am also struggling with this. I am developing on my localhost, I send API request to another one and I get "Access to XMLHttpRequest at 'http://fusio_api_host/customer/login' from origin 'http://localhost' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource".

I've tried setting 'psx_cors_origin' => '*' but it doesn't help. Is there some cache involved? I cleared all the browser cache but no help. Must be something trivial :-)

thx fro any hint

**Comment by colinvv2** [comment]
> Hi, in the admin panel you can set the `CORS` header under settings `cors_allow_origin` and then use `*` or a specific url. Each API response contains then the `Access-Control-Allow-Origin` header.

I do not see this setting in the latest version?
