### ISSUE TITLE
"Scopes" list is empty when a user creates a token

### ISSUE THREAD

**Issue by gpenin** [apioo/fusio#620]
Hi,

Using Fusio API 5.2.1, we found that the "Scopes" list is empty when a user creates a token.

Created token is consequently only attached to the "authorization" scope, and that leads to few "operations" possibilities.

Regards,

![Image](https://github.com/user-attachments/assets/7f39d9e9-2b52-4b27-b9e6-bf5ac4fb0847)

![Image](https://github.com/user-attachments/assets/97902d3a-b883-41dc-84ff-72d04088f102)

**Comment by chriskapp** [comment]
Hi @gpenin can you check which scopes are available at the scopes panel and whether those scopes are also assigned the user which is authenticated, then you should also see those scopes at the token tab.

**Comment by gpenin** [comment]
Hi @chriskapp,

The user was indeed assigned to the scope. I've made another test in case I missed something, but unfortunately, the scope doesn't show at the token tab.

Regards,

![Image](https://github.com/user-attachments/assets/1d28fe00-b710-4d00-86a9-cbc708c200cf)

![Image](https://github.com/user-attachments/assets/dddc6789-6a93-4090-aad6-0d045f9077df)

**Comment by chriskapp** [comment]
@gpenin ok, in general at the token panel you should also see all categories s.

![Image](https://github.com/user-attachments/assets/a6fb5c95-413f-46c0-8fea-4e1d1b7f09ff)

But it looks like this is still the older version where only the list is provided, can you check the network tab to see whether a request is send to the `/consumer/scope/categories` endpoint.

**Comment by gpenin** [comment]
Hi @chriskapp,

No request sent to the [/consumer/scope/categories] endpoint while reaching the token creation form : 

![Image](https://github.com/user-attachments/assets/dbc52f3b-ef39-410a-bbee-41896da584d1)

Regards,

**Comment by chriskapp** [comment]
Hi @gpenin ok it looks indeed like there is a problem with the backend app. We have released yesterday a new version of the backend app s. https://github.com/apioo/fusio-apps-backend/tags I'am not sure about your setup but could you run

```
marketplace:update fusio
```

to get the latest version of the backend app and check whether the problem still exists?

**Comment by gpenin** [comment]
Hi @chriskapp,

We are using a 3 nodes "dockerized" Fusio installation (with Redis cache), and I think we already are in the latest backend app version : 

![Image](https://github.com/user-attachments/assets/fa3c8ada-55f2-4d5c-967a-30cc167ae39d)

Just to make sure we are running the latest versions of all components, I've run a build/destroy/deploy job, but unfortunately, the problem remains.

Regards,

**Comment by chriskapp** [comment]
ok, then you probably using our docker image which still has the old version, your screenshot is only from the marketplace where the current version is shown. If everything goes well I will release a new version today, so that you can get the fix also through the docker image.

**Comment by chriskapp** [comment]
We have just released version 5.2.2 which fixes this problem.
